table Data
	lineageTag: 6ba8cb8a-9237-4335-9360-0f0e619cb2ee

	column OrderKey
		dataType: int64
		formatString: 0
		lineageTag: 7d3ac33e-a4a7-46f7-b2d5-a6179375d538
		summarizeBy: count
		sourceColumn: OrderKey

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 258a11a9-3952-4e59-bf27-c773cf1594d5
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: c7ab1f0d-8e9f-4948-a79d-d30c0da90740
		summarizeBy: count
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column StoreKey
		dataType: int64
		formatString: 0
		lineageTag: 8ae8c7c2-5ad2-47b0-bf3c-ff1bd698823c
		summarizeBy: count
		sourceColumn: StoreKey

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 2d306c66-9278-4788-baac-0603e03c8577
		summarizeBy: count
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: ed3f3903-5667-49e4-8778-059a829b6907
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: f996aace-7a52-446c-b9f3-efdd5bab0f3d
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	partition Data = m
		mode: import
		source = ```
				let
				    Source = Folder.Files("C:\Users\aliso\OneDrive\Documentos\GitHub\csv-to-parquet\csv"),
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Content"}),
				    Custom1 = Table.TransformColumns( #"Removed Other Columns", {{"Content", each Table.PromoteHeaders(Csv.Document(_, [Delimiter=";"])), type {table}}}),
				    Custom2 = Table.Combine( Custom1[Content] ),
				    ChangedType = Table.TransformColumns(
				        Custom2,{
				            {"OrderKey", Number.From, Int64.Type}, 
				            {"CustomerKey", Number.From, Int64.Type}, 
				            {"StoreKey", Number.From, Int64.Type}, 
				            {"ProductKey", Number.From, Int64.Type}, 
				            {"Quantity", Number.From, Int64.Type}, 
				            {"OrderDate", each DateTime.Date(DateTime.From(_)), type date}, 
				            {"UnitPrice", Number.From, Currency.Type}
				        }
				    )
				in
				    ChangedType
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

